# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'auth_front.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_auth(object):
    def setupUi(self, auth):
        auth.setObjectName("auth")
        auth.resize(453, 318)
        self.label = QtWidgets.QLabel(auth)
        self.label.setGeometry(QtCore.QRect(130, 40, 184, 24))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.ok_btn = QtWidgets.QPushButton(auth)
        self.ok_btn.setGeometry(QtCore.QRect(140, 200, 75, 23))
        self.ok_btn.setObjectName("ok_btn")
        self.layoutWidget = QtWidgets.QWidget(auth)
        self.layoutWidget.setGeometry(QtCore.QRect(120, 100, 193, 48))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.name_txt = QtWidgets.QLineEdit(self.layoutWidget)
        self.name_txt.setObjectName("name_txt")
        self.gridLayout.addWidget(self.name_txt, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.pw_txt = QtWidgets.QLineEdit(self.layoutWidget)
        self.pw_txt.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pw_txt.setObjectName("pw_txt")
        self.gridLayout.addWidget(self.pw_txt, 1, 1, 1, 1)
        self.cancel_btn = QtWidgets.QPushButton(auth)
        self.cancel_btn.setGeometry(QtCore.QRect(230, 200, 75, 23))
        self.cancel_btn.setObjectName("cancel_btn")

        self.retranslateUi(auth)
        QtCore.QMetaObject.connectSlotsByName(auth)

    def retranslateUi(self, auth):
        _translate = QtCore.QCoreApplication.translate
        auth.setWindowTitle(_translate("auth", "Dialog"))
        self.label.setText(_translate("auth", "Authentication Panel"))
        self.ok_btn.setText(_translate("auth", "OK"))
        self.label_2.setText(_translate("auth", "User Name"))
        self.label_3.setText(_translate("auth", "Password"))
        self.cancel_btn.setText(_translate("auth", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    auth = QtWidgets.QDialog()
    ui = Ui_auth()
    ui.setupUi(auth)
    auth.show()
    sys.exit(app.exec_())
